
import { Currency } from "@/lib/utils";

export const incomesData = [
  {
    id: 1,
    description: "Pago Proyecto Dashboard",
    date: new Date("2023-06-18"),
    amount: 7500000,
    type: "Cliente",
    client: "Cliente A",
    paymentMethod: "Transferencia",
    receipt: "comprobante-pago-a.pdf",
    notes: "Primer entregable",
    currency: "COP" as Currency,
  },
  {
    id: 2,
    description: "Pago Mensual Mantenimiento",
    date: new Date("2023-06-15"),
    amount: 3800000,
    type: "Cliente",
    client: "Cliente B",
    paymentMethod: "Transferencia",
    receipt: "comprobante-pago-b.pdf",
    notes: "",
    currency: "COP" as Currency,
  },
  {
    id: 3,
    description: "Consultoría UX/UI",
    date: new Date("2023-06-10"),
    amount: 2500000,
    type: "Cliente",
    client: "Cliente C",
    paymentMethod: "Transferencia",
    receipt: "comprobante-pago-c.pdf",
    notes: "Proyecto eCommerce",
    currency: "COP" as Currency,
  },
  {
    id: 4,
    description: "Aporte Capital",
    date: new Date("2023-06-05"),
    amount: 10000000,
    type: "Aporte de socio",
    client: "-",
    paymentMethod: "Transferencia",
    receipt: "comprobante-aporte.pdf",
    notes: "Inversión expansión",
    currency: "COP" as Currency,
  },
  {
    id: 5,
    description: "Desarrollo Landing Page",
    date: new Date("2023-06-03"),
    amount: 1800000,
    type: "Cliente",
    client: "Cliente D",
    paymentMethod: "Tarjeta de Crédito",
    receipt: "factura-cliente-d.pdf",
    notes: "",
    currency: "COP" as Currency,
  },
];

export const monthlyData = [
  { month: "Ene", ingresos: 18700000 },
  { month: "Feb", ingresos: 19500000 },
  { month: "Mar", ingresos: 17600000 },
  { month: "Abr", ingresos: 20800000 },
  { month: "May", ingresos: 22300000 },
  { month: "Jun", ingresos: 25600000 },
];
