// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agheezdpoybazokexrnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnaGVlemRwb3liYXpva2V4cm5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NDc2NDAsImV4cCI6MjA2MTEyMzY0MH0.wR38Y1HUsECdzdIZ4pa-jc3Mwi04AZvdgB4UGBT5VYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);